nerd-animals/na-log-engine

- .github/ISSUE_TEMPLATE/BACKLOG_CREATE.yml
- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/SPRINT_REVIEW.yml
Issue template을 추가하였습니다.
- Resolves: #2 
| 기능  | 스크린샷 |
---
Issue template을 추가하였습니다.
- Backlog
- Bug
- Sprint
> ✨ Issue template 추가

- app/about/page.tsx
- app/page.tsx
about page 추가하였습니다.
- Resolves: #3 
| 기능  | 스크린샷 |
| As-is |![image](https://github.com/nerd-animals/na-log/assets/144116866/eb24530e-3260-44dc-9964-a898f5189da9)|
| To-be |![image](https://github.com/nerd-animals/na-log/assets/144116866/d9977cdc-ab2e-4589-b737-e18f44085181)![image](https://github.com/nerd-animals/na-log/assets/144116866/4bb99e56-eaaf-4f25-a12d-d840e3ea0221)|
---
about 페이지를 추가하여 Link로 ``/about`` 페이지로 갈 수 있게 navigation header를 home 화면에 추가하였습니다.
> ✨ about page 추가

- .vscode/settings.json
- package.json
- tsconfig.json
- yarn.lock
scss package를 설치하였습니다.
- Resolves: #5 
| 기능  | 스크린샷 |
---
css의 원활한 관리를 위해 scss 및 scss 자동완성 package를 설치하였습니다.
[tailwind.css](https://ykss.netlify.app/translation/the_pros_and_cons_of_tailwindcss/#5-css%EB%A5%BC-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EB%B0%B0%EC%9A%B0%EB%8A%94-%EA%B2%83%EC%9D%84-%EB%A7%89%EC%9D%84-%EC%88%98-%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4)
해당 사이트의 ``5.CSS를 제대로 배우는 것을 막을 수 있습니다.`` 를 참고하여 tailwind.css는 css의 이해도를 늘린 후 적용해보는 것으로 결정하였습니다.
> 💬 scss package 설치

- .github/workflows/deploy-to-gh-pages.yml
- next.config.js
> ✨ main branch에 변경점 발생 시, gh-pages branch로 배포 자동화

- README.md
> 📝 README 추가

- app/layout.tsx
- app/page.tsx
css 파일을 scss 파일로 변경하였습니다.
| 기능  | 스크린샷 |
---
css 파일을 scss 파일로 변경하였습니다.
> ♻️ css 파일을 scss로 변경

- app/_components/header.tsx
- app/globals.scss
- app/layout.tsx
header를 component로 만들어주었습니다.
| 기능  | 스크린샷 |
| As-is |![image](https://github.com/nerd-animals/na-log/assets/144116866/86673ae9-2875-48d2-8dad-63e28175a9a0)|
| To-be |![image](https://github.com/nerd-animals/na-log/assets/144116866/1a4526f9-ebeb-4fc5-8f25-463f0d00a337)|
---
header는 재사용을 하기 좋아 component화하였습니다.
_component 폴더를 생성 후('_'는 라우팅이 안됩니다.) header를 component로 만들고 기본적인 css을 적용하였습니다.
> ✨ header component 생성

- app/_components/header.tsx
- app/globals.scss
- app/layout.tsx
전체 레이아웃의 스타일을 중앙 정렬하였습니다.
| 기능  | 스크린샷 |
---
전체 레이아웃을 중앙 정렬하였습니다.
> 💄 전체 레이아웃을 중앙 정렬

- app/_components/footer.tsx
- app/globals.scss
- app/layout.tsx
page footer component 추가하였습니다.
| 기능  | 스크린샷 |
| As-is |![image](https://github.com/nerd-animals/na-log/assets/144116866/9d4e3d20-beac-4113-9b6c-c85391e0ad58)|
| To-be |![image](https://github.com/nerd-animals/na-log/assets/144116866/c6b5e64b-9cf5-4662-b46e-f35e41c9d930)|
---
> ✨ page footer component 추가

- app/layout.tsx
- app/page.tsx
bio component가 소문자였는데, 대문자로 import하고 있어 build 오류가 발생하였습니다.
해당 오류를 수정하였습니다.
| 기능  | 스크린샷 |
---

[컴포넌트 앞글자가 대문자인 이유](https://ko.legacy.reactjs.org/docs/components-and-props.html)
해당 문서 "대문자" 검색하면 나오는 ``주의: 컴포넌트의 이름은 항상 대문자로 시작합니다.`` 주제 참고하여 파일도 앞글자가 대문자인 것이 좋아보여 다른 components들의 앞글자도 대문자로 수정하여 통일성을 맞추어주었습니다.
> 🐛 대문자/소문자 구분으로 인한 wrong path로 생긴 build 오류 수정

- app/_components/PostCard.tsx
- app/globals.scss
- app/page.tsx
post summary를 card형 UI로 home에 추가합니다.
| 기능  | 스크린샷 |
| As-is |![image](https://github.com/nerd-animals/na-log/assets/144116866/9d7809be-6e46-4fe1-ba61-8e2c216d5056)|
| To-be |![image](https://github.com/nerd-animals/na-log/assets/144116866/c0f709d6-a975-4de1-8b22-85ec27266b12)|
---
post summary를 card형 ui로 home에 띄워 추가합니다.
> ✨ post summary card형 UI 추가

- app/about/_components/AboutContent.tsx
- app/about/_components/BlogSection.tsx
- app/about/_components/IntroSection.tsx
- app/about/_components/LineHeader.tsx
- app/about/_components/Member.tsx
- app/about/_components/ProjectSection.tsx
- app/about/_components/TechList.tsx
- app/about/page.tsx
- app/globals.scss
about page를 업데이트하였습니다.
| 기능  | 스크린샷 |
| As-is |![image](https://github.com/nerd-animals/na-log/assets/144116866/519aeb45-db07-4a48-9b78-cfd805010be6)|
| To-be |![image](https://github.com/nerd-animals/na-log/assets/144116866/107878a2-5101-4f04-8bfb-7172f4305fe7)|
---
about page에 팀 소개, 블로그 소개, 프로젝트 내용(예시)을 추가하였습니다.
> ✨ about page에 Intro, Blog, Project 내용 추가

- app/globals.scss
text-align : left 및 justify가 중복되어 있어 제거해주고, 디자인에 맞게 center로 재정렬해주었습니다.
| 기능  | 스크린샷 |
---
left, justify로 중복 정렬되어 있는 부분이 있어 삭제 후 중앙 정렬해야하는 부분은 중앙 정렬 처리해주었습니다.
주석이 달리지 않은 style에 설명을 달아주었습니다.
> 💄 중복 css 제거 및 스타일 설명 주석

- app/page.tsx
main page에 airbnb-style이 자동 저장으로 적용 안된 부분이 있어 적용하였습니다.
> refactor: apply airbnb-style in main page

- next.config.js
- Resolves: #23 
블로그는 블로그 홈페이지 내에서 따로 업데이트해야할 부분이 없기 때문에 ``SSG`` 배포 방식을 적용함에 따라 빌드 시 ``HTML``이 생성됩니다.
따라서, SSR에서의 서버 랜더링이 필요없기 때문에 최적화 옵션을 비활성화하였습니다.
> 🐛 최적화 옵션 비활성화로 이미지 버그 수정

- app/_components/Bio.tsx
- app/globals.scss
home에 bio에 있는 내용을 추가하였습니다.
| 기능  | 스크린샷 |
| As-is |![image](https://github.com/nerd-animals/na-log/assets/144116866/f50d551d-26d4-47a4-904b-9db765d09955)|
| To-be |![image](https://github.com/nerd-animals/na-log/assets/144116866/5339e3c2-98f2-4ce4-8252-a380540aadbc)|
---
- 프로필 사진을 추가하였습니다.
- 사진과 글자의 간격을 조정하였습니다.
- 자기소개 강조해야할 부분을 강조하고, 글자 크기를 키웠습니다.
> ✨ bio 내용 업데이트

- app/_components/PostCard.tsx
- app/globals.scss
- app/page.tsx
- contentlayer.config.js
- posts/0-cat/0-post.mdx
- posts/0-post.mdx
- posts/1-frontend-css.mdx
mdx 포스팅 파일을 home에 있는 postcard ui에 출력하였습니다.
- Resolves: #4 
| 기능  | 스크린샷 |
| As-is |![image](https://github.com/nerd-animals/na-log/assets/144116866/0c7a63ee-f661-4070-b6fd-7b67cceeb3d5)|
| To-be |![24 02 20 link-tag](https://github.com/nerd-animals/na-log/assets/144116866/2b2bfba9-095f-4eae-a913-8dedb7a676df)|
---
- mdx에 summary, date, categories field를 추가하였습니다.
- Link 태그로 postcard와 각각의 상세 포스팅 페이지로 연결되게끔 해주었습니다.
- categories class html이 의도와는 다르게 date와 각각의 categories와 같이 space-between(요소들 사이에 간격을 둠)으로 출력되어, category라는 하위 class html로 분리시켜 그에 맞는 style을 적용시켰습니다.
> ✨ mdx 포스팅 파일을 home에 있는 postcard ui에 출력

- app/globals.scss
- app/post/[...slug]/mdx.scss
- app/post/[...slug]/page.tsx
post/[...slug] 내의 css를 수정하였습니다.
| 기능  | 스크린샷 |
| As-is |![24 02 21 as-is-post](https://github.com/nerd-animals/na-log/assets/144116866/ad639b82-09e2-4642-8981-1005f4b35b79)|
| To-be |![24 02 21 to-be-post](https://github.com/nerd-animals/na-log/assets/144116866/6c348c14-422b-46d2-ba0e-c87293aa2f71)|
---
- 콜아웃 
- 인용구
- 백틱
- 표
- 목록
- 링크
> 💄 post/[...slug] 내 css 업데이트

- contentlayer.config.js
light/dark mode를 삭제함으로써 rehype-pretty-code-theme 미적용 문제를 해결하였습니다.
| 기능  | 스크린샷 |
| As-is |<img width="785" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/9418961b-af78-46dd-bd5c-d5b784e81cd4">|
| To-be |<img width="785" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/44901bb7-7974-41cc-8292-f6099f19eb28">|
---
> 🐛 rehype-pretty-code-theme 미적용 문제 해결

- app/post/[...slug]/mdx.scss
- contentlayer.config.js
code block style을 업데이트하였습니다.
| 기능  | 스크린샷 |
| As-is |<img width="807" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/ceee70b8-31e5-4071-9451-a367552fa701">|
| To-be |<img width="798" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/1064d481-0571-4409-bafc-53a418c1b457">|
---
- code block theme을 가시성이 좀 더 좋은 ``github-dark``으로 변경하였습니다.
- 코드가 블럭 바깥까지 출력되어 글자 사이즈를 줄여주었습니다.
- 코드블럭안의 코드의 여유가 없어 코드블럭 사이즈를 알맞게 조정하였습니다.
> 💄 code block style 업데이트

- app/globals.scss
- app/post/[...slug]/page.tsx
post/[...slug] title 하단부에 date catgegory 항목을 출력하였습니다.
| 기능  | 스크린샷 |
| As-is |<img width="814" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/b7414ccf-b40c-4040-97a3-f7b43d0b852e">|
| To-be |![image](https://github.com/nerd-animals/na-log/assets/144116866/aa150f6b-0fbd-4236-9538-72e30cd77fe8)|
---
> ✨ post/[...slug] title 하단부에 date catgegory 항목 출력

- app/globals.scss
- app/post/[...slug]/page.tsx
- contentlayer.config.js
- posts/0-post.mdx
- posts/1-frontend-css.mdx
post/[...slug] 페이지 제목 하단부에 author를 추가하였습니다.
| 기능  | 스크린샷 |
| As-is |<img width="814" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/40eea392-7edc-4bdd-8de1-e0041c68789b">|
| To-be |![image](https://github.com/nerd-animals/na-log/assets/144116866/f98bfb4c-1ef8-4496-b00d-8239deed51ea)|
---
> ✨ post/[...slug] 페이지 제목 하단부에 author 추가

- app/layout.tsx
- app/post/[...slug]/mdx.scss
- posts/1-frontend-css.mdx
post에서 외부 링크 오른쪽에 링크 icon을 추가하였습니다.
- Resolves: #39 
| 기능  | 스크린샷 |
| As-is |<img width="557" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/1fd0f34a-3c8c-484b-84db-5511f4b82b6d">|
| To-be |<img width="601" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/06a0220f-1d75-4974-8fd5-675fab875595">|
---
외부 링크는 외부 링크임을 명시해주는 것이 구독자 입장에서 좀 더 편해보입니다.
> 💄 post에서 외부 링크 오른쪽에 링크 icon 추가

- posts/1-frontend-css.mdx
외부 링크에 새 탭으로 열기 기능을 추가하였습니다.
- Resolves: #40 
| 기능  | 스크린샷 |
| As-is |![24 02 22 orginal-tab](https://github.com/nerd-animals/na-log/assets/144116866/cc9692cb-68e9-4a9d-b1ae-a932fc3d5ecc)|
| To-be |![24 02 22 new-tab](https://github.com/nerd-animals/na-log/assets/144116866/7a7af5f7-5441-4b7c-839e-f3e791a4f1ba)|
---
a 태그에 target="_blank"를 추가함으로써 외부 링크에 새 탭으로 열기 기능을 추가하였습니다.
> ✨ 외부 링크에 새 탭으로 열기 기능 추가

- README.md
README에 paste image extension 설치 이유 및 사용 설명을 추가하였습니다.
- Resolves: #44 
추후 블로그를 배포하거나 할 때, 해당 기능의 사용 방법이 있어야되므로 내용 추가하였습니다.
> 📝 paste image extension 설치 이유 및 사용 설명 추가

- app/post/[...slug]/page.tsx
post 날짜란 왼쪽에 달력 아이콘을 추가했습니다.
| 기능  | 스크린샷 |
| As-is |<img width="255" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/d89beb40-73fd-4cc8-9e1a-619a92a4de09">|
| To-be |<img width="255" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/33aa6a47-399a-4abc-ab3c-1d3873fb0372">|
---
> 💄 post 날짜란 왼쪽에 달력 아이콘 추가

- app/_components/PostCard.tsx
- app/globals.scss
- posts/otter/main/sub/1-frontend-css.mdx
post card ui 스타일을 변경하였습니다.
| 기능  | 스크린샷 |
| As-is |<img width="850" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/6c97169a-e887-4069-880a-d229b05b5cfa">|
| To-be |<img width="850" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/55975ed5-5b9e-4cc4-83b5-a2a96ce38375">|
---
- post와 가장 가까운 category 하나만 title 위에 출력하도록 했습니다.
- summary를 150줄 이하로 제한함에 따라 2줄로 출력되도록 하였습니다.
- tags와 date를 post/[...slug] 페이지와 비슷한 레이아웃으로 변경하였습니다.
> 💄 post card ui 스타일 변경

- app/globals.scss
- app/post/[...slug]/page.tsx
✨ post/[...slug]에 categories 출력
| 기능  | 스크린샷 |
| As-is |<img width="842" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/ff49d1a4-8b07-41e7-85c0-8c40ad854ff8">|
| To-be |<img width="842" alt="image" src="https://github.com/nerd-animals/na-log/assets/144116866/9f708bd1-12e0-48ba-b316-73d804897fbb">|
---
> ✨ post/[...slug]에 categories 출력

- app/_components/PostCard.tsx
- app/post/[...slug]/page.tsx
category 내용이 dev mode에서 새로고침 시 바뀌거나 잘못된 데이터로 build 되는 에러를 수정하였습니다.
- Resolves: #68
| 기능  | 스크린샷 |
| As-is |![24 02 23 pop()error](https://github.com/nerd-animals/na-log/assets/144116866/1c56941c-8c44-4465-a34e-c62ce8311b39)|
| To-be |![24 02 23 pop()error-fix](https://github.com/nerd-animals/na-log/assets/144116866/bbec9e71-d233-4951-8cd1-852c7984718e)|
---
본래 ``pop()``으로 array의 맨 마지막 데이터를 출력해주었으나,
[react 공식 문서](https://ko.react.dev/learn/updating-arrays-in-state)에 따르면, react에서 배열 내부 항목을 재할당하는 것은 재렌더링 및 성능 문제로 좋지 않은 방법입니다. 때문에 array의 [length - 1]로 출력해주는 것으로 변경하였습니다.
> 🐛 category 내용이 dev mode에서 새로고침 시 바뀌거나 잘못된 데이터로 build 되는 에러 수정

- app/_components/PostCard.tsx
- app/globals.scss
- app/post/[...slug]/page.tsx
category는 하나 혹은 한 그룹으로 출력되기 때문에 categories classname을 category로 변경하였습니다.
(ex: otter, otter/python, otter/front-end/css)
> 💬 categories classname을 category로 변경

- app/_styles/mdx.scss
- contentlayer.config.js
post/[...slug] style를 업데이트하였습니다.
- anchor에 링크 아이콘을 넣었습니다.
- a style에 transition을 넣어주었습니다.
> 💄 post/[...slug] style 업데이트

- .github/workflows/deploy-to-gh-pages.yml
- next.config.js
> ♻️ 환경변수를 통해 basePath 설정하도록 변경

- app/_components/Bio.tsx
- app/_styles/globals.scss
bio 프로필 사진, 소개글 유무로 사용자 커스텀화 기능을 추가하였습니다.
---
- bio 프로필 사진, 소개글이 각각 없을 시 그리고 둘 다 없을 때 정상적으로 조건에 맞게 출력되도록 하였습니다.
- 사진 없이 소개글 단독이더라도 사진과 같은 세로폭을 화면에서 차지하도록 하였습니다.
> ✨ bio 프로필 사진, 소개글 유무로 사용자 커스텀화 기능 추가

- page-item/bio.mdx
현재 빌드된 홈페이지에 image가 출력되지 않아 bio image path를 수정하였습니다.
> 🐛 bio image path 수정

- app/_components/Bio.tsx
bio.mdx가 없을 때 bio 에러를 수정하였습니다.
[optional chaining](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining)문법을 이용하여 bio가 undefined 조건일 때도 처리해주었습니다.
> 🐛 bio.mdx가 없을 때 에러 수정

- app/_components/PostCard.tsx
- app/page.tsx
post card component 구조를 단일화하였습니다.
- Resolves: #60 
> ♻️ post card component 구조 단일화

- app/_components/PostCard.tsx
post card props type을 interface로 명시하였습니다.
type을 코드의 가독성 및 타입 체크를 좀 더 용이하게 하기 위하여 [interface style guide](https://basarat.gitbook.io/typescript/styleguide#interface)에 맞게  interface으로 정의해주었습니다.
>  ♻️ post card props type을 interface로 정의

- .env
- .github/workflows/deploy-to-gh-pages.yml
- app/_components/Header.tsx
- app/layout.tsx
- next.config.js
- public/config.json
사용자에 따라 달라지는 값을 설정할 수 있도록 변경
- $GITHUB_REPOSITORY : github actions에 설정된 default 변수 `owner/repository`
- 위의 변수를 이용함으로써 사용자가 따로 설정해주지 않아도 된다.
- title : meta data, 좌측 상단 Home title
- description : meta data
- giscuss
> ♻️ 환경 변수 설정 방법 변경

- .env
- app/_components/Header.tsx
- app/layout.tsx
- next.config.js
public 내 파일이고, build time에만 있으면 되기 때문에 fetch가 아닌 import로 변경
basePath를 GITHUB_REPOSITORY에 따라 동적으로 설정하게 됨.
따라서, 로컬에서 테스트할 때에 굳이 basePath를 꼭 설정해줄 필요가 없음.
테스트하고 싶다면, `.env.local`에 `<Owner>/<Repo>` 형태로 설정해서 테스트 가능
> 🐛 config.json fetch 에러

- contentlayer.config.js
삭제되지 않았던 패키지 제거
| 기능  | 스크린샷 |
---
> 🐛 사용하지 않는 패키지 삭제

- app/_components/MdxComponent.tsx
- posts/how-to/0-image.mdx
> ✨ img to image 태그 변경

- app/post/[...slug]/page.tsx
- Resolves: #106
| 기능  | 스크린샷 |
---
> 🐛 build error when empty post

- app/post/[...slug]/page.tsx
array.push() -> return type이 number였음.
return type을 제대로 신경 못 써서 발생한 이유
| 기능  | 스크린샷 |
---
> 🐛 return type error

- .github/workflows/deploy-to-gh-pages.yml
> 💬 develop에 변경점 발생했을 때, workflow 동작하도록 변경

- contentlayer.config.js
- package.json
- yarn.lock
포스팅 작성 편의를 위해 제거
| 기능  | 스크린샷 |
---
> 💬 remark-breaks 제거
